### ISSUE TITLE
List All Product Categories returns image.src: false

### ISSUE THREAD

**Issue by azrin640** [woocommerce/wc-api-node#100]
API => GET:  products/categories?per_page=20

returns the below listed data which does not include category image src, refer attachment;
`image: {
    alt: false,
    name: "Hello world!",
    src: false, ...
}
![Screenshot from 2019-04-24 19-42-10](https://user-images.githubusercontent.com/7897022/56656840-1cd9b480-66c9-11e9-8cbc-cabb6aa595de.png)

`

**Comment by claudiosanches** [comment]
This library is now deprecated, you should try https://github.com/woocommerce/woocommerce-rest-api-js-lib
