### ISSUE TITLE
Remove coupon or fee in Order

### ISSUE THREAD

**Issue by JMalaval** [woocommerce/wc-api-node#101]
Hi,

I need to remove a coupon or a fee in my Order with Rest API and I can't find how do this .
I try this to set fee_lines to null but it just do nothing

```
let order = {
    fee_lines: null
};

woocommercePlugin.putAsync('orders/10' , order)
```

```
let order = {
    fee_lines: []
};

woocommercePlugin.putAsync('orders/10' , order)
```

How can I delete a fee/coupon in an order if i can't update it to null or something like that ?

Thanks You very much :)

**Comment by claudiosanches** [comment]
This library is now deprecated, you should try https://github.com/woocommerce/woocommerce-rest-api-js-lib
