### ISSUE TITLE
woocommerce_rest_cannot_batch

### ISSUE THREAD

**Issue by jmawebtech** [woocommerce/wc-api-node#102]
Hi,

I am trying to create product variations in a batch. My code works with other customers, so I believe this is a site specific issue. My user generated new keys and logged into the site as admin.

https://www.littlewomentoo.com/wc-api/v3/products?filter[limit]=50&filter[sku]=83105&page=1&consumer_key=X&consumer_secret=X

POST https://www.littlewomentoo.com/wp-json/wc/v2/products/121246/variations/batch?consumer_key=X&consumer_secret=X HTTP/1.1
Accept: application/json
Content-Type: application/json
User-Agent: JMA Web Technologies
Authorization: Basic X
Host: www.littlewomentoo.com
Content-Length: 293
Expect: 100-continue

{"create":[{"attributes":[{"id":2,"name":"Size","slug":"size","visible":true,"variation":true,"option":"5"},{"id":1,"name":"Color","slug":"color","visible":true,"variation":true,"option":"grey"}],"sku":"194004","regular_price":"67.99","stock_quantity":0.0,"taxable":true,"manage_stock":true}]}

HTTP/1.1 401 Unauthorized
Server: nginx
Date: Mon, 13 May 2019 19:32:49 GMT
Content-Type: application/json; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-cache
Pragma: no-cache
X-Robots-Tag: noindex
Link: <https://www.littlewomentoo.com/wp-json/>; rel="https://api.w.org/"
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Access-Control-Allow-Headers: Authorization, Content-Type
Set-Cookie: PHPSESSID=kioeet93bcf8g95nk6sl25l7n0; path=/
Set-Cookie: bronx_popup=1; expires=Tue, 14-May-2019 19:32:49 GMT; Max-Age=86400; path=/

﻿{"code":"woocommerce_rest_cannot_batch","message":"Sorry, you are not allowed to batch manipulate this resource.","data":{"status":401}}

**Comment by claudiosanches** [comment]
This library is now deprecated, you should try https://github.com/woocommerce/woocommerce-rest-api-js-lib
