### ISSUE TITLE
Filter parameter issue

### ISSUE THREAD

**Issue by sh-guti** [woocommerce/wc-api-node#39]
Sending request with this endpoint
`products?filter[tax_query][0][taxonomy]=product_brand&filter[tax_query][0][field]=slug&filter[tax_query][0][terms][0]=adidas`
The request is actually sent to
`http://my-domain.com/wp-json/wc/v1/products?filter%5Btax_query%5D%5B0%5D%5Bfield%5D=slug&filter%5Btax_query%5D%5B0%5D%5Btaxonomy%5D=product_brand&filter%5Btax_query%5D%5B0%5D%5Bterms%5D%5B0%5D=adidas&oauth_consumer_key=ck_26faeaf9f02b235c4cc547e77e8c14f6c07c2eec&oauth_nonce=DqiZopJKGuiXdug6IHYQ9cLNZZ6IT7gd&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1475085829&oauth_version=1.0&filter%5Btax_query%5D%255B0%255D%255Bfield%255D=slug&filter%5Btax_query%5D%255B0%255D%255Btaxonomy%255D=product_brand&filter%5Btax_query%5D%255B0%255D%255Bterms%255D%255B0%255D=adidas&oauth_signature=wyYTV7aitqK9hlkJgESe6gJbrpZCAlJgvxyEcmM5020%3D`
notice the filter parameter is duplicated twice.
and i get an error:
{"code":"woocommerce_rest_authentication_error","message":"Invalid Signature - provided signature does not match.","data":{"status":401}}

I think there is an issue with oAuth library

Using latest WC version WP-Rest api

**Comment by claudiosmweb** [comment]
Need to sort the parameters by name.

**Comment by sh-guti** [comment]
Thanks.
I thought you were fixed it [3e29898](https://github.com/woocommerce/wc-api-node/commit/3e298981975a071bd1848fad97c99614a722a784)
Using ssl url working fine
