### ISSUE TITLE
No support for React native!

### ISSUE THREAD

**Issue by ariesborne** [woocommerce/wc-api-node#40]
I am trying to use this npm module for my react native project and it wouldn't work.
When i try to import the module, it throws the error shown in the screen shot. please Fix this. i am stuck because of this error. I tried all the solution shown for this error.. still not working.

![simulator screen shot 26-sep-2016 7 24 45 pm](https://cloud.githubusercontent.com/assets/20890218/18981553/1f136510-86fd-11e6-8029-2d5a22d6735e.png)

**Comment by claudiosmweb** [comment]
Feel free to submit a Pull Request to enable support for React Native.
Thanks.

**Comment by Valindo** [comment]
Is the issue fixed?

**Comment by claudiosanches** [comment]
@Valindo feel free to submit a Pull Request to help with it.

**Comment by toastyghost** [comment]
+1
