### ISSUE TITLE
How to get On sale product using REST API ?

### ISSUE THREAD

**Issue by billyriantono** [woocommerce/wc-api-node#42]
Hi Team,
I am on using wc-api-node, when i am try to get all on sale product using endpoint /products in current version woocommerce api ( v1)  and add filter['on_sale']=true it's doesn't give me the correct result.

anyone can help me to do this ?

Thanks

**Comment by claudiosmweb** [comment]
https://github.com/woocommerce/woocommerce/issues/12093#issuecomment-253774850
