### ISSUE TITLE
"woocommerce_rest_cannot_view" and 401 Unauthorised

### ISSUE THREAD

**Issue by HelloTiago** [woocommerce/wc-api-node#43]
When using the new REST API I keep getting a `woocommerce_rest_cannot_view` error. I double checked everything as per the API and this package's documentation and code but couldn't find anything wrong with my setup.

Here's the code I'm using:

		import WooCommerceAPI from 'woocommerce-api';
		
		var WooCommerce = new WooCommerceAPI({
			url: 'https://192.168.22.10.xip.io',
			wpAPI: true,
			version: 'wc/v1',
			consumerKey: 'ck_5cd77...',
			consumerSecret: 'cs_b54c...',
			verifySsl: false
		});

		WooCommerce.get('products', function(err, data, res) {
		  console.log(res);
		});

I tried setting the permalinks, creating new keys, changing the URL... nothing fixed it.

When I test this via Paw (API tool for Mac) using Basic Auth and the exact same parameters though, it works perfectly! I get a SSL certificate dialog similar to Safari's, choose to continue and the request is processed perfectly.

I'm guessing the "verifySsl" option isn't doing it's job? What else can I try?

**Comment by claudiosanches** [comment]
> I'm guessing the "verifySsl" option isn't doing it's job? What else can I try?

You should read an error message about the invalid SSL certificate and not getting a `woocommerce_rest_cannot_view`.
This can happens when your server is not configured properly and it's not reading the authentication headers, so you should use `queryStringAuth: true`.

**Comment by HelloTiago** [comment]
Thanks for the reply.

I tried that too, I get the same error `woocommerce_rest_cannot_view`...

**Comment by claudiosanches** [comment]
So there's something wrong with your installation, REST API keys or server.
But this is not an issue with this REST API lib.

**Comment by HelloTiago** [comment]
That's pretty weird since the request works perfectly via Paw. I've tried running this on a different server in Apache (rather than Nginx) and it still doesn't work via the lib - continues to work via Paw without any special config, just the parameters & basic auth.

**Comment by HelloTiago** [comment]
Tried a few different things with this and noticed something interesting:

The request to get "products" continues to return a 401 error, but if I make the request to the API index, it works!

This works:
```
WooCommerce.get('', function(err, data, res) {
  console.log(res);
});
```

This returns a 401 error:
```
WooCommerce.get('products', function(err, data, res) {
  console.log(res);
});
```

Does this give you any idea of what may be happening?

**Comment by claudiosanches** [comment]
Works because the index don't requests authentication.

**Comment by sco-tt** [comment]
Came across here via google and the minor server modifications (Issue 4, solution 1) worked for me: https://robotninja.com/blog/fix-common-woocommerce-rest-api-issues/

**Comment by funkaki** [comment]
Woocommerce class-wc-rest-authentication::authenticate() ([class-wc-rest-authentication](https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-authentication.php)) uses Wordpress is_ssl() to check what type of authentication should be used (oauth1 or basic auth). 
For some reason [is_ssl()](https://codex.wordpress.org/Function_Reference/is_ssl#notes) might not work correctly and oauth1 is used, although authentication provided is for basic auth.

**Comment by gabrielfojo** [comment]
This was my solution, hopes it works 
https://help.robotninja.com/getting-started/woocommerce-api-authentication-issues

**Comment by kotlandroid** [comment]
be sure that apache return authorization header, in `http.conf` add this `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`
