### ISSUE TITLE
Invalid Signature

### ISSUE THREAD

**Issue by dciccale** [woocommerce/wc-api-node#44]
Hi, I just installed woocommerce-api, created new api keys (api is enabled) in woocommerce and did a simple call to get orders and test it, but I'm getting this error:

```json
{"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]}
```

```js
const WooCommerce = require('woocommerce-api');

const wooCommerce = new WooCommerce({
  url: 'http://example.com/index.php',
  consumerKey: 'ck_33a6316baf347629067389cccfb574b5433f0bf6',
  consumerSecret: 'cs_5ae71218180dd1a0fdfe6d21baf12f88fb23c338'
});

wooCommerce.get('orders', (err, res, body) => {
  console.log(body);
  // {"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]}
});
```

request parameters

```js
{ url: 'http://example.com/index.php/wc-api/v3/orders',
  method: 'GET',) 
  encoding: 'utf8',
  timeout: undefined,
  headers: 
   { 'User-Agent': 'WooCommerce API Client-Node.js/1.4.0',
     'Content-Type': 'application/json',
     Accept: 'application/json' },
  qs: 
   { oauth_consumer_key: 'ck_33a6316baf347629067389cccfb574b5433f0bf6',
     oauth_nonce: 'SRQbsOIP3KnGsUjKj5Lu5RWsprEH9J9k',
     oauth_signature_method: 'HMAC-SHA256',
     oauth_timestamp: 1478204724,
     oauth_version: '1.0',
     oauth_signature: 'WMAJ1JQb6WJvJFpuVyXMMGsTO8Wg5QYtOrfCyGsy+BY=' } }
```

any clues?

**Comment by dciccale** [comment]
Wordpress Version 4.6.1
WooCommerce Version 2.6.7

**Comment by dciccale** [comment]
I also tried passing this config, and many other variants, still no luck

```js
  wpAPI: true,
  wpAPIPath: 'wp-rest/',
  version: 'wc/v1',
```

**Comment by dciccale** [comment]
Finally, it worked with this config setup

```js
  consumerKey: 'ck_33a6316baf347629067389cccfb574b5433f0bf6',
  consumerSecret: 'cs_5ae71218180dd1a0fdfe6d21baf12f88fb23c338',
  version: 'wc/v1',
  wpAPI: true,
  wpAPIPrefix: 'wp-json'
```

**Comment by dciccale** [comment]
unbelievable none of this is documented on how to setup auth for different api versions

**Comment by claudiosanches** [comment]
https://woocommerce.github.io/woocommerce-rest-api-docs/?javascript#libraries-and-tools

![screenshot from 2016-11-04 22-37-34](https://cloud.githubusercontent.com/assets/1264099/20026255/5621dd7c-a2df-11e6-816f-4aee37313c80.png)

If you use `https` will apply Basic Auth, but all our examples of configuring the library is with `http` that uses oAuth1.0a.

And no need for `wpAPIPrefix: 'wp-json'` if you are not changing the API prefix path.

**Comment by dciccale** [comment]
Excellent now the readme has been updated, 👍

**Comment by claudiosanches** [comment]
@dciccale we always have on the readme "Check out the WooCommerce API endpoints and data that can be manipulated in http://woocommerce.github.io/woocommerce-rest-api-docs/.", and this "Custom WP REST API URL prefix, used to support custom prefixes created with the `rest_url_prefix` filter".
