### ISSUE TITLE
JS Client Returns 401; Postman returns 200

### ISSUE THREAD

**Issue by nathanaelphilip** [woocommerce/wc-api-node#45]
```
var WooCommerceAPI = require('woocommerce-api');
//import WooCommerceAPI from 'woocommerce-api';

let WooCommerce = new WooCommerceAPI({
    url: 'http://data.uikit.dev',
    wpAPI: true,
    consumerKey: 'ck_df9b0cb9f1c7aa8eb04ae05b4cca3097e8f8693c',
    consumerSecret: 'cs_61da879ea10f7a3d815006cad6452560a1e28e8a',
    version: 'wc/v1',
});

WooCommerce.get('products', function(err, data, res) {
    console.log(err);
    console.log(res);
});
```

If I put the same info into PostMan, it works just fine – it even works if I grab the URL from Chrome’s network tab, but the JS returns a 401 error.

QuickCast: http://quick.as/j2GQim38g

Is this still a server issue?

**Comment by nathanaelphilip** [comment]
I think it may be a CORS issue, since I’m trying to access it via `uikit.dev`. i’ll leave this open just incase.

**Comment by nathanaelphilip** [comment]
seems like it’s the same as this: https://github.com/woocommerce/woocommerce/issues/9395

**Comment by claudiosanches** [comment]
Well, CORS issue is on your server and not in this wrapper.
About Postman this depends on how are you testing, are you really using oAuth1.0 on postman?

**Comment by nathanaelphilip** [comment]
@claudiosanches i think it’s strictly a CORS issue, but was unable to resolve.

**Comment by cherijs** [comment]
I was having the same problem!

![screen shot 2016-12-08 at 20 38 21](https://cloud.githubusercontent.com/assets/2779993/21022725/4e2f0556-bd86-11e6-81c2-d51ae4ac1917.png)

When opened requested url it worked! 
![screen shot 2016-12-08 at 20 40 11](https://cloud.githubusercontent.com/assets/2779993/21022789/89d2e668-bd86-11e6-98cb-d610cdfa4b26.png)



Then i tryed to recreate same request.  After some experiments it worked without headers or just without 'Content-Type': 'application/json', 

```javascript
  var post_url = WooCommerce._getOAuth().authorize({
    url: 'http://data.paviljons.com/wp-json/wc/v1/products',
    method: 'GET'
  });


  var options = {
    method: 'GET',
    url: 'http://data.paviljons.com/wp-json/wc/v1/products',
    headers: {
      'User-Agent': 'WooCommerce API Client-Node.js/1.4.0',
      // PROBLEM IS HERE!!!!
      // 'Content-Type': 'application/json', 
      Accept: 'application/json'
    },
    qs: post_url
  };

  request(options, function ( error, response, body ){
    if ( error ) {
      throw new Error(error);
    }

    console.log(body);
  });
```


![screen shot 2016-12-08 at 20 46 07](https://cloud.githubusercontent.com/assets/2779993/21023009/65fa834e-bd87-11e6-83f3-b896948cc0df.png)

**Comment by claudiosanches** [comment]
@cherijs your issue is not the same of this here.
