### ISSUE TITLE
reactnative woocommerce api

### ISSUE THREAD

**Issue by Yoyo-DI** [woocommerce/wc-api-node#46]
Hi ,
I'm trying to integrate WooCommerceAPI in react-native project 
First , i encountered a problem with crypto module wich is installed but when running the app i get an error "Module crypto not found"
 Then, i installed crypto-js and  used rn-nodeify to resolve this issue, then i runned the project again i get , "Object prototype may only be an object or null "

I don't know what does this error mean? 

Thanks

**Comment by claudiosanches** [comment]
This is not a support channel. And looks like you did not installed this module dependencies.
