### ISSUE TITLE
Do you still maintaining this?

### ISSUE THREAD

**Issue by davidvexel** [woocommerce/wc-api-node#47]
Have this issue:

 `[$injector:unpr] Unknown provider: WPProvider <- WP <- mycontroller`

Thank you! It's hard to find a good library for angular and wc api.

**Comment by claudiosanches** [comment]
> 2016-09-28 - v1.4.1 - Updated dependencies and updated/fixed oAuth1.0a.

And I'll update today, so here is your answer.
