### ISSUE TITLE
Error: Invalid JSON Body passed

### ISSUE THREAD

**Issue by HelloTiago** [woocommerce/wc-api-node#48]
Seems like there's a WP Core issue with v4.7 where a "invalid_json_body" error is returned by the API if the request has no body, which is the case with `WooCommerce.get` requests.

See the [core issue here](https://core.trac.wordpress.org/ticket/39150).

Same thing on the [WC API PHP Wrapper](https://github.com/woocommerce/wc-api-php/issues/68) and apparently removing the Content-Type header [works as a temporary fix](https://github.com/bryceadams/wc-api-php/commit/7b27f5e346a7bfed47df987fedab77dc65f51923) - any chance the same can be done here, while WP 4.7.1 isn't released? Or is there another workaround? Thanks!

**Comment by bryceadams** [comment]
@HelloTiago you'd have to do the same as my suggestion in there and remove the content type header as a temporary solution.

**Comment by claudiosanches** [comment]
Fix included into 1.4.2.
Thanks for report it.
