### ISSUE TITLE
Error: Cannot find module "../package.json"

### ISSUE THREAD

**Issue by anivaisu** [woocommerce/wc-api-node#49]
I'm working on integrating Woocommerce Rest API with Ionic 2 using this package: 

npm install --save woocommerce-api

import * as WooCommerceAPI from 'woocommerce-api';

 ionViewDidLoad() {
var WooCommerce = new WooCommerceAPI({
      url: 'http://example.com',
      consumerKey: 'ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      consumerSecret: 'cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    });
}
I'm getting this error and app stops running.
Error: Cannot find module "../package.json"
Pls Advice me,
Thanks & Regards,

**Comment by claudiosanches** [comment]
We don't call `"../package.json"` in any place, looks like this error it's coming from somewhere else.
Good luck.
