### ISSUE TITLE
Invalid parameter(s): billing, shipping for the woocommerce-api: "1.4.2"

### ISSUE THREAD

**Issue by shaikhussian** [woocommerce/wc-api-node#51]
Hai ,
  I am using the woocommerce module, It was awesome working before updating my wordPress to version 4.7.1, But from the new version i.e 4.7.1 it is not showing the correct response it throws the error like 

> Invalid parameter(s): billing, shipping 
> version which i used for woocommerce-api: "1.4.2"

Here is **my code**
```
app.post('/api/createOrder',function(req,res){
  var data = req.body
  WooCommerce.post('orders', data, function(order, data, res1) {
    console.log(res1);
    var json=JSON.parse(res1)
    res.send(json)
  });
})
```
**In req.body which i passed is**
```
{
  "payment_method": "bacs",
  "payment_method_title": "Direct Bank Transfer",
  "set_paid": true,
  "billing":{
    "first_name": "John",
    "last_name": "Doe",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US",
    "email": "john.doe@example.com",
    "phone": "(555) 555-5555"
  },
  "shipping": {
    "first_name": "John",
    "last_name": "Doe",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US"
  },
  "line_items": [
    {
      "product_id": 938,
      "quantity": 2
    }
  ],
  "shipping_lines": [
    {
      "method_id": "flat_rate",
      "method_title": "Flat Rate",
      "total": 10
    }
  ]
}
```
**wordPress Version:4.7.1**
**woocommerce-api version:1.4.2**
Please give me suggestion that how can i solve this. Thanking You

**Comment by claudiosanches** [comment]
Looks that is working just fine.
Note that here is not a support channel for the WooCommerce REST API.
If you need help with WooCommerce REST API you can use the community forum: https://wordpress.org/support/plugin/woocommerce
