### ISSUE TITLE
Webpack errors

### ISSUE THREAD

**Issue by emilsgulbis** [woocommerce/wc-api-node#52]
Hello!

Having errors when trying to use npm package in Webpack build.

```
Module not found: Error: Can't resolve 'net' in '***/node_modules/forever-agent'
 @ ./~/forever-agent/index.js 6:10-24
 @ ./~/request/request.js
 @ ./~/request/index.js
 @ ./~/woocommerce-api/index.js
 @ ./assets/scripts/bootstrap.js
 @ ./assets/scripts/main.js
ERROR in ./~/forever-agent/index.js
```

Also Module not found and can't resolve 'tls' and 'fs'

There is something I've missed?

**Comment by emilsgulbis** [comment]
Maybe there is way to use WooCommerce with official WP API javascript client - models and collections?

**Comment by andrewmclagan** [comment]
yeah also having this issue with WC-API client and webpack.

**Comment by claudiosanches** [comment]
@emilsgulbis fell free to submit a Pull Request.

**Comment by itjunkii83** [comment]
Hi, 

Has anyone made any progress on this issue?

**Comment by chi11ax** [comment]
+1 have this problem too ....

**Comment by ruucm** [comment]
## Here is how I solved it.
```
npm i --save request &&  npm i --save-dev json-loader
```

add below config to your webpack

```
  node: {
    console: true,
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
  },
```

## Ref
[link](https://github.com/request/request/issues/1529)

**Comment by glemigobles** [comment]
@ruucm
I had same issue - that helped me. Thanks!

**Comment by claudiosanches** [comment]
It should be possible with https://github.com/woocommerce/woocommerce-rest-api-js-lib
