### ISSUE TITLE
Webhooks: what is the topic for the restore action?

### ISSUE THREAD

**Issue by LeCoupa** [woocommerce/wc-api-node#53]
When I restore a product previously put to trash, it does not trigger an `updated` or `created` webhook. Is there a way to detect this behavior?

<img width="613" alt="screen shot 2017-02-11 at 11 28 23 pm" src="https://cloud.githubusercontent.com/assets/1658644/22858346/85130bd0-f0b2-11e6-84bb-8c00946e5fcb.png">

**Comment by claudiosanches** [comment]
Sorry, but here is not a support channel for the REST API.
Try https://wordpress.org/support/plugin/woocommerce
