### ISSUE TITLE
401 Unauthorized error when posting.

### ISSUE THREAD

**Issue by rishab121** [woocommerce/wc-api-node#54]
I am able to make get calls with it successfully but when I try to post it gives me 401 invalid signature error.

my code for Ionic 2.
 var WooCommerce = new WooCommerceAPI({
      url: 'http://vishaljoshi.in/woocommerce',
      consumerKey: 'ck_',
      consumerSecret: 'cs_',
      wpApi: true,
      version: 'wc/v1',
      wpAPIPrefix: 'wp-json'            
   })

   WooCommerce.post('customers', this.data, function(err, data, res) {
   console.log(res);
  });
// Am i missing something here?

**Comment by fahad-nxvt** [comment]
@rishab121 what was the issue? i am facing the same problem can you please guide me please?

**Comment by rishab121** [comment]
I wasn't able to resolve issue with the node.js wrapper. so instead of directly posting data from Ionic to woocommerce; I posted the data from Ionic to python api (bottle) and then used python wrapper to post data to woocommerce server.
