### ISSUE TITLE
Not returning full list of products

### ISSUE THREAD

**Issue by ageddesi** [woocommerce/wc-api-node#55]
Hi All, 

Can anyone explain to my why this is not working and returning a full list of products. 

```
WooCommerce.get('products', function(err, data, res) {
        if (res !== null) {
            allItems = JSON.parse(res);
        }
    });
```

it appears to be only returning 10 products.

**Comment by claudiosanches** [comment]
Sorry, but here is not a support channel for the WooCommerce REST API.

**Comment by claudiosanches** [comment]
> it appears to be only returning 10 products.

And the WooCommerce REST API docs already have instructions about it.
