### ISSUE TITLE
"nonce is already used"

### ISSUE THREAD

**Issue by natanavra** [woocommerce/wc-api-node#57]
Using the NodeJS woocommerce-api package + woocommerce 3.0.0 + wp 4.7.4.

- Tried multiple endpoints, product related, e.g.: http://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-a-product
- Tried multiple API keys with different permissions and different users.
- Not using https.

Getting "nonce is invalid, already used" error "woocommerce_api_authentication_error".

- Tried curl but getting "401 - woocommerce_rest_cannot_view".

Any advice?

**** UPDATE ****

Using the node package 'woocommerce' which is not official from the woocommerce team and uses the legacy API -> works well!

**Comment by claudiosanches** [comment]
This could be related to the timezone from where you are doing requests and the shop timezone.
Are you using a different timezone?

Should be always more easy if using HTTPS, will avoid a lot of errors like it.

**Comment by natanavra** [comment]
Hi Claudio,
The server is in USA and I'm in a GMT+3 timezone, but doesn't it work on UTC timestamp? I've checked the times sync it's exactly 3 hours difference.

Don't have the option to install an SSL certificate at the moment, any other workarounds?

**Comment by dan7554** [comment]
A fix for this would be greatly appreciated!

**Comment by claudiosanches** [comment]
@dan7554 please feel free to submit a Pull Request.

**Comment by claudiosanches** [comment]
@natanavra I need to check the timestamps, not sure now if uses UTC or not.

**Comment by claudiosanches** [comment]
This library is now deprecated, you should try https://github.com/woocommerce/woocommerce-rest-api-js-lib
