### ISSUE TITLE
Invalid timestamp

### ISSUE THREAD

**Issue by KingWu** [woocommerce/wc-api-node#58]
`{ code: 'woocommerce_api_authentication_error',
dynamics-export-app |        message: 'Invalid timestamp' }`

I get this authentication issue. But, no idea on this issue.

Woocommece Version: 2.5.5
Wordpress version: 4.5.2

Any one know it?

**Comment by thiagofalencar** [comment]
I had the same problem... In my case, was because of the server time.
You can try again after synchronizing the time of server using ntpdate comand...
