### ISSUE TITLE
woocommerce-api - unable to load module

### ISSUE THREAD

**Issue by kasjolaj** [woocommerce/wc-api-node#59]
Hi,

I´m all new to woocommerce-api. I keep getting this error:

SCRIPT5022: Module name 'woocommerce-api' has not been loaded yet for context: _
http://requirejs.org/docs/errors.html#notloaded
require.js (1634,9)

I´m trying to create a new customer with the following code:

var WooCommerceAPI = require('woocommerce-api');

            var WooCommerce = new WooCommerceAPI({
                url: 'http://url-to-wp-installation',
                consumerKey: 'ck_a1575eca815c15874b92f1f4c8db207147228a0a',
                consumerSecret: 'cs_c332c64e1ecb1701b46fb659a35699a276c8c28a',
                wpAPI: true,
                version: 'wc/v1'
            });

            var data = {
                email: '[e-mail address',
                password: '[password]',
                first_name: '[FirstName',
                last_name: '[LastName]',
                Username: '[UserName]'
            };

            WooCommerce.post('customers', data, function (err, data, res) {
                
            });

**Comment by claudiosanches** [comment]
Works just fine, maybe you are loading too late in your app.
