### ISSUE TITLE
woocommerce_api_authentication_error

### ISSUE THREAD

**Issue by lsantaniello** [woocommerce/wc-api-node#61]
Hy guys,
I have a problem with communicate with my wordpress/woocommerce store. I installed it in my local machine. I invoke the service inside my ionic app.

`     this.WooCommerce = WC({
      url: "http://localhost/wordpress",
      consumerKey: "ck_7681851dd851c8b5eacd7cda61e5fc6cb997a653",
      consumerSecret: "cs_e4ee5f928c6ae1d0243478bb95b6d71f6ce3d5aa"
    });`

CALL 1
`    this.WooCommerce.getAsync("products").then( (data) => {
      console.log(data);
    }, (err) => {
      console.log(err);
    })`

CALL 2
`this.WooCommerce.postAsync('customers', customerData).then( (data) => {
      console.log(data);
    }, (err) => {
      console.log(err);
    })`

CALL 1 works but CALL 2 always return the following error (in italian language):

`{"errors":[{"code":"woocommerce_api_authentication_error","message":"Firma non valida - la firma fornita non corrisponde."}]}`

Could you please help me?
Thanks

Luca

**Comment by koubeissy-ibrahim** [comment]
i have the same issue any solution plz

**Comment by rafa-acioly** [comment]
same error, try this yesterday with some extra parameters: `wpAPI: true` and `version: 'wc/v1'`

**Comment by isma907** [comment]
Hello Guys i have the same problem,
Im triying to test this in my localhost and my wordpress site is running on HTTP
This is my TEST.js file

`var WooCommerceAPI = require('woocommerce-api');
var application_root = __dirname;
var express = require( 'express' ),
var path = require('path');

app= express();
app.use(express.static('public'))

app.get('/', function (req, res) {
  res.sendFile(path.join(__dirname + '/index.html'));
})

app.get('/getProducts', function (req, res) {
  var WooCommerce  = new WooCommerceAPI({
    url: 'http://my-site/woocommerce',
    consumerKey: 'ck_f5bd16b12292c9d2e7b59a2e88650b139c43c499',
    consumerSecret: 'cs_8ede46974b2a449e049e741394109dc5cebbccfa',
    version: 'wc/v1',
    verifySsl:false,
    wpAPI:true
  });

  WooCommerce.get('products', function(err, data, response) {
    res.send(JSON.stringify(data,response))
  });
})
`

My error:
> woocommerce_rest_authentication_error","message":"Invalid signature - provided signature does not match.","data":{"status":401}}

Thanks

**Comment by benjaminspi** [comment]
I dont know if it help, but I use 'wc/v2' ... is there a reason why you use v1?

**Comment by isma907** [comment]
I find the problem!
I dont know why...but work for me.

Just add the WWW after the http  :D 
good luck !

**Comment by rafa-acioly** [comment]
@isma907 still not working here, are you using local environment?

**Comment by isma907** [comment]
Yes im using a Local enviroment with a custom vhost 
on windows modify 

`C:\Windows\System32\drivers\etc\hosts (run notepad as administrator)`

add this on the last line
`127.0.0.1       your-local-domain.com
`
```
\\SERVER FILE.JS
express = require( 'express' ),
vhost = require( 'vhost' );
function createVirtualHost(domainName, dirPath) {
    return vhost(domainName, express.static( dirPath ));
}
//Create server
var app = express();
//Create the virtual hosts
var desarrollo = createVirtualHost("http://www.your-local-domain.com", "your-local-domain");


  var WooCommerce  = new WooCommerceAPI({
    url: 'http://www.your-local-domain.com',
    consumerKey: 'ck_XXX',
    consumerSecret: 'cs_XXX',
    wpAPI: true,
    version: 'wc/v1'
  });
```

**Comment by rafa-acioly** [comment]
I'm using `ember server` as local env. Right now i'm making some tests using `postman` and it works only if i use `Type` as "Oauth 1.0", how can i set this using the npm package?

![print-screen](http://www.putimg.net/pictures/1499109557.png)

**Comment by rafa-acioly** [comment]
i've tested in my application (emberjs) and using postman, keep getting the same error, all parameters are passed to header normally, but the signature still invalid using the package.

![print-network](http://www.putimg.net/pictures/1499270482.png)

![print-postman](http://www.putimg.net/pictures/1499270511.png)

**Comment by claudiosanches** [comment]
@rafa-acioly this shows that the problem is not in this REST API library, since you are using Postman and getting the same error, sounds like the problem is in your WooCommerce installation.

**Comment by rafa-acioly** [comment]
@claudiosanches the error is "invalid signature" if i use postman with another signature that not come from the package the API works fine.

**Comment by rafa-acioly** [comment]
https://github.com/ef4/ember-browserify/issues/120#issuecomment-313853855
