### ISSUE TITLE
New fix of your library

### ISSUE THREAD

**Issue by PikinerLiliya** [woocommerce/wc-api-node#62]
Hi all, we are developing synchronization of ERP System with WooCommerce and use your library. 

We got 401 error:

{ code: 'woocommerce_rest_authentication_error',
message: 'Invalid Signature - provided signature does not match.',
data: { status: 401 } }

and have fix for it.

Please, contact us.

**Comment by claudiosanches** [comment]
Feel free to submit a Pull Request if you have a fix.
