### ISSUE TITLE
Order with payment status "paid" do not remove products from stock

### ISSUE THREAD

**Issue by rafa-acioly** [woocommerce/wc-api-node#64]
If i send a `order` with the payment status `true` the products are not removed from stock.

```js
 let data = {
    payment_method: 'cod',
    payment_method_title: 'Pagamento na loja',
    set_paid: true,
   ...
```

The order are created successfully but when i go check if the stock is lower nothing happened, if i don't use the parameter `set_paid` the product stock are refreshed e evething works just fine.

**Comment by claudiosanches** [comment]
Our questions does not sounds like related to this REST API library, better ask questions about WooCommerce REST API on https://wordpress.org/support/plugin/woocommerce
