### ISSUE TITLE
post method sending as "options"

### ISSUE THREAD

**Issue by rafa-acioly** [woocommerce/wc-api-node#68]
I know there are several endpoints and they are "Post" and "Options", I am currently trying to make a "post" to create a new order and when I check the request, the method is listed as "Options" when I use "Post":

```
Request URL:http://wc-project.dev/wp-json/wc/v1/orders?oauth_consumer_key=ck_93a7e4148b5a44d2df769c7ec84e95160a58412f&oauth_nonce=YAPYM17tgDlZ4jjrvOG3G51JG4EeL8LX&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1501358327&oauth_version=1.0&oauth_signature=raioD7xbHPenMO1HvJsWrxAFwA0dHzx6%2F%2FSiq2BWRn4%3D
Request Method:OPTIONS
Status Code:401 Unauthorized
Remote Address:127.0.0.1:80
```

This causes me to receive an error:

> OPTIONS http://wc-project.dev/wp-json/wc/v1/orders?oauth_consumer_key=ck_93a7e4148b…ion=1.0&oauth_signature=raioD7xbHPenMO1HvJsWrxAFwA0dHzx6%2F%2FSiq2BWRn4%3D 

> Fetch API cannot load http://wc-project.dev/wp-json/wc/v1/orders?oauth_consumer_key=ck_93a7e4148b…ion=1.0&oauth_signature=raioD7xbHPenMO1HvJsWrxAFwA0dHzx6%2F%2FSiq2BWRn4%3D. Response for preflight has invalid HTTP status code 401

When I access the first link of "options" I received a json informing that the signature is invalid, but anyway, the method I'm using is "post"

```js
const wooAPI = new WooCommerceAPI({
	url: 'http://wc-project.dev/',
	consumerSecret: 'cs_687837928550ef3e17362e32d92300d3c7e336f7',
	consumerKey: 'ck_93a7e4148b5a44d2df769c7ec84e95160a58412f',
	wpAPI: true,
	verifySsl: false,
	version: 'wc/v1'
});

wooAPI.post('orders', fakeOrderData, function(err, data, res) {
      console.log(res);
});
```

When I make a "get" call, I have not received any errors regarding signing or authorization. The API keys I'm using have read and write permission.

![](http://www.putimg.net/pictures/1501359071.png)

**Comment by rafa-acioly** [comment]
sorry, miss click*

**Comment by hassan-kk** [comment]
Same here, has any of you found a solution ?

**Comment by claudiosanches** [comment]
Maybe something on your server, because this REST API library does not change the request terms.
I just make a test and works just fine.
