### ISSUE TITLE
Getting Error Connection Refused when accessing woocommerce-api

### ISSUE THREAD

**Issue by Andriy-Kulak** [woocommerce/wc-api-node#70]
Hi Team,

I am getting the following error when running a simple example. It worked sometimes before but more recently I am getting the error consistently.
```
ERROR { Error: connect ECONNREFUSED 192.***PORT_NUMBER***
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.***ANOTHER_PORT_NUMBER***',
  port: 443 }
ERROR MESSAGE ===== connect ECONNREFUSED 192.***PORT_NUMBER***
```
When I look at the base API, I get normal responses. You can check it too, my website is: https://artpriority.io/wc-api/v2/

**Does anyone know what the potential problem can be?**

Below is the example code. I run it in node.

I tried again just now and it sent a regular response the first two times and then started throwing the same error again!
```
    const WooCommerceAPI = require('woocommerce-api');

    const WooCommerce = new WooCommerceAPI({
      url: 'https://artpriority.io',
      consumerKey: '*** key ***',
      consumerSecret: '*** secret ***',
      wpAPI: true,
      version: 'wc/v2'
    });

    WooCommerce.get(`products/29588`, (err, data, res) => {
      if(err) {
        console.log("ERROR", err);
        console.log("ERROR MESSAGE =====", err.message);
      } else {
        console.log("RESPONSE ==========", res);
      }
    });
```

**Comment by claudiosanches** [comment]
This issue don't sound related to this REST API library.
Need to check your server or plugins installed, but this REST API library can not cause the problem that you are reporting.
