### ISSUE TITLE
Feature Request: Pagination example

### ISSUE THREAD

**Issue by florianbepunkt** [woocommerce/wc-api-node#72]
@claudiosanches 

Could you please add a pagination example? I would like to retreive all orders for a month – not knowing in advance how many orders / pages of orders there will be. I'm having trouble with the pagination. The `headers.link` property does not only contain the url for the next request, but also also a rel=next parameter. I'm sure this is by design. But I wonder how you would use this to chain requests so you get all pages available. Or how do you handle paginated requests?

**Comment by florianbepunkt** [comment]
Okay, I have a solution… but it feels kind of hacky, so the initial feature request for the documentation still stands.

I parse the link header and then have to remove part of the request url so I can recursively run the same request until I fetched all documents.

```
'use strict';

if(process.env.NODE_ENV !== 'production') {
  require('dotenv').config()
}

const _ = require('lodash');
const parse = require('parse-link-header');
const WooCommerceAPI = require('woocommerce-api');

const wc = new WooCommerceAPI({
  url: process.env.WOOCOMMERCE_HOST,
  consumerKey: process.env.WOOCOMMERCE_KEY,
  consumerSecret: process.env.WOOCOMMERCE_SECRET,
  wpAPI: true,
  version: 'wc/v2',
  queryStringAuth: true
});

/**
 * gets all orders in recursive function
 * @method getAll
 * @param  {[type]} request [description]
 * @return {[type]}         [description]
 */
function getAll(request) {
  return wc.getAsync(request).then((response) => {
    let parsed = parse(response.headers.link);

    if (!parsed.next) {
      return JSON.parse(response.body);
    } else {
      parsed.next.url = parsed.next.url.replace(process.env.WOOCOMMERCE_HOST + '/wp-json/wc/v2/', '');
    }

    return Promise.all([
      JSON.parse(response.body),
      getAll(parsed.next.url)
    ]).then((responses) => {
      return _.flatten(responses);
    });
  }).catch((ex) => {
    console.log(ex);
  });
}

// call the function
getAll('orders?per_page=10')
  .then((orders) => {
    console.log(JSON.stringify(orders, null, 3));
    console.log(orders.length)
  })
```

**Comment by claudiosanches** [comment]
There is no example to get all pages at the same time.
And what you did on your example is correct.
