### ISSUE TITLE
get products?page=1

### ISSUE THREAD

**Issue by prostoVladislav** [woocommerce/wc-api-node#80]
Hello.
how can I send a request for one page?

```
            this.$wcAPI.getAsync('products?page=1').then((result) => {

            });
```

https://i.imgur.com/NjmyUH5.png
https://i.imgur.com/4sGZAW5.png
https://i.imgur.com/laH5M6D.png
https://woocommerce.github.io/woocommerce-rest-api-docs/?javascript#pagination

**Comment by prostoVladislav** [comment]
upd. fix
line 82 change to 
  params.forEach(function(item) {
    if (queryString.length) {
      queryString += '&';
    }

    queryString += encodeURIComponent(item).replace('%5B', '[').replace('%5D', ']');
    queryString += '=';
    queryString += encodeURIComponent(query[item]);
  })


but have new issue. headers not available( X-WC-TotalPages: etc...)

**Comment by claudiosanches** [comment]
This library is now deprecated, you should try https://github.com/woocommerce/woocommerce-rest-api-js-lib
