### ISSUE TITLE
create product take more than 2 minutes 

### ISSUE THREAD

**Issue by elgreatly** [woocommerce/wc-api-node#81]
i try to create a products by woocommerce-api in nodejs it takes more than 2 minutes to add only 10 products 

i need a solution for this i think it should take just 1,2 second at most to add 50 product

`
WC.put('products/batch', data, function(err, data, res) {
       console.log(res);
 });
`

**Comment by claudiosanches** [comment]
The time will depends on the server configuration where you are submitting those products, this may take some times depending in the server.
