### ISSUE TITLE
Woocommerce rest authentication error - Invalid Signature

### ISSUE THREAD

**Issue by whyengineering** [woocommerce/wc-api-node#82]
**CORS .htaccess** :
`header set Access-Control-Allow-Origin "*"
header set Access-Control-Allow-Headers "origin,content-type,user-agent, accept, x-r$"
header set Access-Control-Allow-Methods "PUT,GET,POST,DELETE,OPTIONS,HEAD"`

**API Request** :
`http://192.168.1.125/badlapur/wp-json/wc/v2/orders?oauth_consumer_key=ck_fe1859072d41b36ed511ba6a4e31de75aac16516&oauth_nonce=I7DfkcQvMIST8aKnGqSEHk2NsCKTljWs&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1515179933&oauth_version=1.0&oauth_signature=Ru3%2BDd1zz1ihRqGhbeoYasbLZkzNGZqtb5I61UJi1Kw%3D
`
**Json Response**:
```
{
"code": "woocommerce_rest_authentication_error",
"message": "Invalid signature - provided signature does not match.",
   "data": {
      "status": 401
   }
}
```

**I am using wordpress with following plugins**:

> JSON API
> JSON API USER
> WooCommerce

I activated Settings->JSON API->Core & User I re-created consumer key & secret
But still not working, any way to solve?

**Comment by saadmomin** [comment]
Facing the same issue. Please share the solution if you have managed to resolve it.

**Comment by gyanly** [comment]
Facing the same issue. Please share the solution if you have managed to resolve it.

**Comment by margox** [comment]
+1

**Comment by champsxs** [comment]
Did anyone find a solution? I'm struggling with this for a long time.  My local copy of the site works fine with same API request mentioned by @MiBi-Tech. But when I connect it to prod hosted in AWS things break :(

**Comment by johandekruijf** [comment]
I found out that you should use the exact same URL to connect to the API as is used in the Wordpress settings.

**Comment by mondalaci** [comment]
Oddly, I can connect without problems via HTTPS, but I got the

```
{ errors: 
   [ { code: 'woocommerce_api_authentication_error',
       message: 'Invalid signature - provided signature does not match.' } ] }
```

error when connecting via HTTP on localhost.

I ended up debugging this problem, and realized that when using HTTP, this package uses OAuth. WordPress expected the following OAuth base string:

```
GET&http%3A%2F%2Flocalhost%2Fwc-api%2Fv3%2Forders&oauth_consumer_key%3Dck_196592934272939402342301020401ab02342123%26oauth_nonce%3DenodPx3mukAIkWwzi3B5KFGOdpncO2xp%26oauth_signature_method%3DHMAC-SHA256%26oauth_timestamp%3D1537897356%26oauth_version%3D1.0%26q%3D%252Fwc-api%252Fv3%252Forders
```

But this package doesn't send the end of the expected string:

`%26q%3D%252Fwc-api%252Fv3%252Forders`

Which equals to the following when urldecoded:

`&q=%2Fwc-api%2Fv3%2Forders`

Which equals to the following when urldecoded:

`&q=/wc-api/v3/orders`

Given the above realization, I can make this library connect over HTTP if I replace the

`return crypto.createHmac('sha256', key).update(base_string')`

line with:

`return crypto.createHmac('sha256', key).update(base_string+'%26q%3D%252Fwc-api%252Fv3%252Forders')`

Can you guys recommend a proper fix that makes this library work without hacking it?

**Comment by mondalaci** [comment]
I ended up fixing this for myself: https://github.com/mondalaci/wc-api-node/commit/a7b1438e7cfdef02622cab245129111edf895146

Not sending a PR, because I highly doubt it's a general fix, but it works for me.

**Comment by ElegantSoft** [comment]
I have same issue 
I found solution
you need to put customer_key and secret in url as parameter even if you make POST request 
and no authurization

**Comment by mondalaci** [comment]
@ElegantSoft Can you provide a code sample?

**Comment by claudiosanches** [comment]
This library is now deprecated, you should try https://github.com/woocommerce/woocommerce-rest-api-js-lib
