### ISSUE TITLE
problem in post request get request is working fine

### ISSUE THREAD

**Issue by gyanly** [woocommerce/wc-api-node#86]
problem in post request get request is working fine....
![errro](https://user-images.githubusercontent.com/26550271/36636638-7b4e5236-19f0-11e8-867a-9f14ed0085fd.png)
please help me solving this problem..

**Comment by IntelliJAbhishek** [comment]
@gyanly same problem have you found the solution?

**Comment by gyanly** [comment]
yes use  https:// insted of http:// solved all problem.
during development use this chroem plugin https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?utm_source=chrome-app-launcher-info-dialog
for header acess controll error






sidebar//// when this plugin enabled youtube video may not play, so disable this plugin when you play video on youtube

**Comment by claudiosanches** [comment]
This library is now deprecated, you should try https://github.com/woocommerce/woocommerce-rest-api-js-lib
