### ISSUE TITLE
Unable retrieve coupon data using coupon code getAsync

### ISSUE THREAD

**Issue by rifrayugo** [woocommerce/wc-api-node#88]
I am trying to retrieve coupon data using coupon code, previously i am using request to fetch the coupon data by coupon code. That's running well.
Now i am trying to use wc-api-node to fetch data with getAsync function the respose always like this
`  body: '{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}' }` 
This is my configuration and my code to fetch coupon data.
```
var WooCommerceAPI = require('woocommerce-api');
var WooCommerce = new WooCommerceAPI({
  url: 'https://xcidictest.000webhostapp.com',
  consumerKey: 'ck_2b0ba82c93657bxxxxx',
  consumerSecret: 'cs_5ff3267d182d1xxxxx',
  wpAPI: true,
  version: 'wc/v2'
});
var data = {
  code: '10off',
  discount_type: 'percent',
  amount: '10',
  individual_use: true,
  exclude_sale_items: true,
  minimum_amount: '100.00'
};
WooCommerce.getAsync('coupons/code/10off').then(function(result) {
  console.log(result);
  // return JSON.parse(result.toJSON().body);
});

**Comment by claudiosanches** [comment]
This library is now deprecated, you should try https://github.com/woocommerce/woocommerce-rest-api-js-lib
