### ISSUE TITLE
"rest_missing_callback_param", in ionic 3 

### ISSUE THREAD

**Issue by chiranjitkuiry** [woocommerce/wc-api-node#90]
![screenshot 25](https://user-images.githubusercontent.com/22238776/38782357-e50d1086-410f-11e8-857f-13a7f8154042.png)
AND HERE IS THE CODE 
signup(){

      let customerData = {

        customer : {}
      }

      customerData.customer = {
        "email": this.newUser.email,
        "first_name": this.newUser.first_name,
        "last_name": this.newUser.last_name,
        "username": this.newUser.username,
        "password": this.newUser.password,
        "billing_address": {
          "first_name": this.newUser.first_name,
          "last_name": this.newUser.last_name,
          "company": "",
          "address_1": this.newUser.billing_address.address_1,
          "address_2": this.newUser.billing_address.address_2,
          "city": this.newUser.billing_address.city,
          "state": this.newUser.billing_address.state,
          "postcode": this.newUser.billing_address.postcode,
          "country": this.newUser.billing_address.country,
          "email": this.newUser.email,
          "phone": this.newUser.billing_address.phone
        },
        "shipping_address": {
          "first_name": this.newUser.first_name,
          "last_name": this.newUser.last_name,
          "company": "",
          "address_1": this.newUser.shipping_address.address_1,
          "address_2": this.newUser.shipping_address.address_2,
          "city": this.newUser.shipping_address.city,
          "state": this.newUser.shipping_address.state,
          "postcode": this.newUser.shipping_address.postcode,
          "country": this.newUser.shipping_address.country
        }
      }

      if(this.billing_shipping_same){
        this.newUser.shipping_address = this.newUser.shipping_address;
      }
      

      this.WooCommerce.postAsync('customers',customerData).then( (data) => {

        let response = (JSON.parse(data.body));
//IGNORE CLOSING BRACKETS

**Comment by chiranjitkuiry** [comment]
solved, The rest api endpoint has to change

**Comment by claudiosanches** [comment]
This library is now deprecated, you should try https://github.com/woocommerce/woocommerce-rest-api-js-lib
