### ISSUE TITLE
How to get all products for a specific category?

### ISSUE THREAD

**Issue by PssThemes** [woocommerce/wc-api-node#91]
I see in documentation that you can get either all products.
Or all categories.
I cant find a way in which to get only the products from a specific category.

so far i've been using: 
```
https://ecom.pssthemes.com/woocommerce/wp-json/wc/v2/products?consumer_key=key&consumer_secret=secret&filter[product_cat]="decor"
```

```
https://ecom.pssthemes.com/woocommerce/wp-json/wc/v2/products?consumer_key=key&consumer_secret=secret&filter[category]="decor"
```
etc.. cant find anything [in the docs](https://woocommerce.github.io/woocommerce-rest-api-docs/?shell#list-all-product-categories) .
Ive tried this in postman.. but also with the library itself.. no success. The code is: 
```
WooCommerce.get('products?filter[category]="decor"', function(err, data, res) {
  console.log(res);
});
```
So far i can't decide if this feature does not exist.. or i'm missing something.

Would you consider adding functionality for this specific use-case? 
To me seems very basic to have the ability to get all the products for only 1 category.. Thanks:)

**Comment by edersign** [comment]
Hi, 

Use a category id to list all products.

```
WooCommerce.getAsync('products?category=1').then((data) => {
      console.log(JSON.parse(data.body));
      products = JSON.parse(data.body);
}, (err) => {
      console.log(err)
}) 
```

**Comment by paltanmoy** [comment]
Hi @PssThemes ,

You can easily get it using category id 

```
WooCommerce.get('products?category=<categoryID>’, function(err, data, res) {
 	console.log(res);
});
```

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs this REST API library and is not a support forum for WooCommerce REST API. If you have questions about the WooCommerce REST API you should ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce
