### ISSUE TITLE
Passing boolean in parameters not working

### ISSUE THREAD

**Issue by heartseeker** [woocommerce/wc-api-node#93]
Trying to get all featured products with this piece of code but it returns all products instead.

`wooCommerce.getAsync('products?featured=' + true).then(function(result) {
        res.json(JSON.parse(result.toJSON().body));
    });`

**Comment by claudiosanches** [comment]
This library is now deprecated, you should try https://github.com/woocommerce/woocommerce-rest-api-js-lib
