### ISSUE TITLE
missing meta_data in the response 

### ISSUE THREAD

**Issue by paltanmoy** [woocommerce/wc-api-node#96]
I am not able to get the meta_data parameter in the JSON response while getting the product details. 
Though using python api (https://pypi.org/project/WooCommerce/) I am able to get the meta_data parameter as expected. 

Any idea ?

**Comment by hamedebr** [comment]
I'v the same problem with meta_data..all item
`
                    WooCommerce.putAsync(`products/${item.id}`,{
                        name:"another",
                        meta_data:[{
                            id:2000,
                            key:"isCustomImage",
                            value:"true"
                        }]
                    })
`

but meta_data not appears in responded object

**Comment by hamedebr** [comment]
Damn!
I found out what's going on!
meta_data is supported on v2 no v1 and npm documentation should be updated.
`
var WooCommerce = new WooCommerceAPI({
  url: 'http://example.com',
  consumerKey: 'ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  consumerSecret: 'cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  wpAPI: true,
  **version: 'wc/v2'**
});
`
`
