### ISSUE TITLE
origin blocked by CORS 

### ISSUE THREAD

**Issue by sdipto1** [woocommerce/wc-api-node#97]
i am trying to test ionic app on browser with wc-api-node. it show me origin blocked by CORS issue. i have add proxies still same issue 
![capture](https://user-images.githubusercontent.com/34346432/51798147-15c11880-2238-11e9-8cbb-d45551732dc2.JPG).

**Comment by kbehov** [comment]
Add this code to youre functions.php -->
function add_cors_http_header(){
    header("Access-Control-Allow-Origin: *");
	header('Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, READ');
	header('Access-Control-Allow-Headers: Origin, Content-Type, X-Auth-Token,authorization,XMLHttpRequest, user-agent, accept');
   header("Access-Control-Allow-Credentials: true"); 

    if ( 'OPTIONS' == $_SERVER['REQUEST_METHOD'] ) {
        status_header(200);
        exit();
    }
}
add_action('init','add_cors_http_header');

**Comment by sdipto1** [comment]
Thnak you for your quick response.
I have used the above code, in my thems/functions.php file but i have found this errors.

![capture](https://user-images.githubusercontent.com/34346432/51900237-ff08f600-23de-11e9-971c-9b640002b895.JPG)
![1](https://user-images.githubusercontent.com/34346432/51900245-03cdaa00-23df-11e9-874e-afc83e1c1f6c.JPG)

**Comment by kbehov** [comment]
Change header("Access-Control-Allow-Origin: *"); to
header("Access-Control-Allow-Origin: http://localhost:8100");

**Comment by rowellfortune** [comment]
Thanks this worked

**Comment by kbehov** [comment]
Happy to hear that!

**Comment by claudiosanches** [comment]
This library is now deprecated, you should try https://github.com/woocommerce/woocommerce-rest-api-js-lib
